development:
  adapter:  postgres
  database: development
  username: postgres
  password: 
  host:     localhost
  port:     5432
  encoding: UTF-8

test:
  adapter:  postgres
  database: test
  username: postgres
  password: 
  host:     localhost
  port:     5432
  encoding: UTF-8

production:
  adapter:  postgres
  database: production
  username: postgres
  password: 
  host:     localhost
  port:     5432
  encoding: UTF-8